name: factlm
channels:
  - defaults
dependencies:
  - ipython=7.22.0
  - jupyter=1.0.0
  - matplotlib=3.3.4
  - numpy=1.20.1
  - pandas=1.2.4
  - pip=21.0.1
  - python=3.7.10
  - scikit-learn
  - scipy=1.6.2
  - seaborn=0.11.1
  - tqdm=4.59.0
  - yaml=0.2.5
  - pip:
    - gitpython==3.1.18
    - gputil==1.4.0
    - hydra-core==1.1.0
    - jsonlines==2.0.0
    - nlpaug==1.1.7
    - omegaconf==2.1.0
    - torch==1.4.0
    - transformers==3.5.0
    - wandb==0.10.32
